// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingExample.proto

package cn.shuaijunlan.grpc.leagning.streaming;

public interface AverageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streaming.Average)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double val = 1;</code>
   */
  double getVal();
}
