// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingExample.proto

package cn.shuaijunlan.grpc.leagning.streaming;

public interface MetricOrBuilder extends
    // @@protoc_insertion_point(interface_extends:streaming.Metric)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 1;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

  /**
   * <code>int64 metric = 2;</code>
   */
  long getMetric();
}
