// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: StreamingExample.proto

package cn.shuaijunlan.grpc.leagning.streaming;

public final class StreamingExample {
  private StreamingExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streaming_Metric_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streaming_Metric_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_streaming_Average_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_streaming_Average_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026StreamingExample.proto\022\tstreaming\032\037goo" +
      "gle/protobuf/timestamp.proto\"G\n\006Metric\022-" +
      "\n\ttimestamp\030\001 \001(\0132\032.google.protobuf.Time" +
      "stamp\022\016\n\006metric\030\002 \001(\003\"\026\n\007Average\022\013\n\003val\030" +
      "\001 \001(\0012D\n\016MetricsService\0222\n\007collect\022\021.str" +
      "eaming.Metric\032\022.streaming.Average(\001BB\n&c" +
      "n.shuaijunlan.grpc.leagning.streamingB\020S" +
      "treamingExampleP\001\242\002\003SJLb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_streaming_Metric_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_streaming_Metric_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streaming_Metric_descriptor,
        new java.lang.String[] { "Timestamp", "Metric", });
    internal_static_streaming_Average_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_streaming_Average_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_streaming_Average_descriptor,
        new java.lang.String[] { "Val", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
