/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_shuaijunlan_java_basic_learning_jni_JNITest */

#ifndef _Included_cn_shuaijunlan_java_basic_learning_jni_JNITest
#define _Included_cn_shuaijunlan_java_basic_learning_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_shuaijunlan_java_basic_learning_jni_JNITest
 * Method:    testJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_shuaijunlan_java_basic_learning_jni_JNITest_testJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
