  javah cn.shuaijunlan.java.basic.learning.jni.JNITest

  g++ -fPIC -shared -I /usr/lib/jvm/java-8-openjdk-amd64/include/ -I /usr/lib/jvm/java-8-openjdk-amd64/include/linux/ cn/shuaijunlan/java/basic/learning/jni/JNITest.cpp -o cn/shuaijunlan/java/basic/learning/jni/libhello_JNI.so

  java -Djava.library.path=cn/shuaijunlan/java/basic/learning/jni/ cn.shuaijunlan.java.basic.learning.jni.JNITest